name: dawa
description: Flutter widget implementing DAWA, Danmarks Adressers Web API
version: 0.0.1+1
repository: https://github.com/taisph/flutter_dawa

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.0-0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
